variable "aws_region" {
  description = "AWS region for the demo stack."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Short project name used in resource names and tags."
  type        = string
  default     = "govcon-captureos"
}

variable "environment" {
  description = "Deployment environment label."
  type        = string
  default     = "demo"
}

variable "vpc_cidr" {
  description = "IPv4 CIDR for the low-cost demo VPC."
  type        = string
  default     = "10.42.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "Two public subnet CIDRs. Lambda and RDS are both placed here to avoid NAT gateways."
  type        = list(string)
  default     = ["10.42.0.0/24", "10.42.1.0/24"]

  validation {
    condition     = length(var.public_subnet_cidrs) == 2
    error_message = "Exactly two public subnet CIDRs are required."
  }
}

variable "db_name" {
  description = "Initial PostgreSQL database name."
  type        = string
  default     = "captureos"

  validation {
    condition     = can(regex("^[A-Za-z][A-Za-z0-9_]{0,62}$", var.db_name))
    error_message = "db_name must start with a letter and contain only alphanumeric characters or underscores."
  }
}

variable "db_username" {
  description = "RDS PostgreSQL master username. The password is generated by Terraform to avoid a hard-coded value."
  type        = string
  default     = "captureos"

  validation {
    condition     = can(regex("^[A-Za-z][A-Za-z0-9_]{0,62}$", var.db_username))
    error_message = "db_username must start with a letter and contain only alphanumeric characters or underscores."
  }
}

variable "postgres_engine_version" {
  description = "PostgreSQL engine version. Keep on 15+ for pgvector support through the database migration."
  type        = string
  default     = "15"

  validation {
    condition     = can(regex("^(1[5-9]|[2-9][0-9])(\\..*)?$", var.postgres_engine_version))
    error_message = "postgres_engine_version must be PostgreSQL 15 or newer."
  }
}

variable "lambda_functions" {
  description = "Lambda deployment artifacts and runtime settings. The api key is wired to API Gateway HTTP API."
  type = map(object({
    package_path         = string
    source_code_hash     = optional(string)
    handler              = string
    runtime              = optional(string, "python3.12")
    memory_size          = optional(number, 256)
    timeout              = optional(number, 20)
    reserved_concurrency = optional(number)
    vpc_enabled          = optional(bool, true)
    environment          = optional(map(string), {})
  }))

  default = {
    api = {
      package_path = "../../dist/captureos_api.zip"
      handler      = "src.lambda_api.handler"
      runtime      = "python3.12"
      memory_size  = 256
      timeout      = 30
      environment = {
        APP_MODULE = "src.api_v1_endpoints:app"
      }
    }

    proposal_writer = {
      package_path = "../../dist/captureos_api.zip"
      handler      = "src.proposal_writer_lambda.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 256
      timeout      = 300
      vpc_enabled  = false
      environment = {
        AWS_USE_DUALSTACK_ENDPOINT               = "false"
        LOG_LEVEL                                = "INFO"
        PROPOSAL_ESCALATION_MAX_TOKENS           = "2800"
        PROPOSAL_ESCALATION_READ_TIMEOUT_SECONDS = "240"
        PROPOSAL_FALLBACK_MAX_TOKENS             = "2200"
        PROPOSAL_FALLBACK_READ_TIMEOUT_SECONDS   = "30"
        PROPOSAL_HELPER_TIMEOUT_SECONDS          = "8"
        PROPOSAL_WRITER_MAX_TOKENS               = "2000"
        PROPOSAL_WRITER_READ_TIMEOUT_SECONDS     = "240"
      }
    }

    ingest = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.gsa_api_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 60
      vpc_enabled  = false
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    upsert = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.gsa_api_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 60
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    awards_ingest = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.usaspending_awards_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 90
      vpc_enabled  = false
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    awards_upsert = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.usaspending_awards_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 90
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    subawards_ingest = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.usaspending_subawards_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 90
      vpc_enabled  = false
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    subawards_upsert = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.usaspending_subawards_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 90
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    calc_ingest = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.gsa_calc_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 90
      vpc_enabled  = false
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    calc_upsert = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.gsa_calc_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 90
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    resolver = {
      package_path = "../../dist/captureos_resolver.zip"
      handler      = "src.entity_resolver_lambda.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 256
      timeout      = 30
      environment = {
        ENTITY_RESOLUTION_AUTO_MATCH_SCORE = "0.91"
      }
    }

    db_admin = {
      package_path = "../../dist/captureos_db_admin.zip"
      handler      = "src.db_admin_lambda.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 256
      timeout      = 120
      environment = {
        LOG_LEVEL = "INFO"
      }
    }
  }

  validation {
    condition     = contains(keys(var.lambda_functions), "api")
    error_message = "lambda_functions must include an api function for API Gateway integration."
  }

  validation {
    condition     = alltrue([for fn in values(var.lambda_functions) : contains([128, 256], fn.memory_size)])
    error_message = "Each Lambda memory_size must be 128 or 256 MB for this low-cost demo profile."
  }

  validation {
    condition     = alltrue([for fn in values(var.lambda_functions) : fn.reserved_concurrency == null || (fn.reserved_concurrency >= 10 && fn.reserved_concurrency <= 25)])
    error_message = "When set, reserved_concurrency must be 10-25 so AWS keeps its required unreserved concurrency pool."
  }
}

variable "lambda_layer_arns" {
  description = "Optional dependency layers for psycopg2, FastAPI/Mangum, boto3 extras, or pgvector client packages."
  type        = list(string)
  default     = []
}

variable "lambda_log_retention_days" {
  description = "CloudWatch Logs retention for Lambda logs. Short retention prevents silent storage creep."
  type        = number
  default     = 7
}

variable "bedrock_model_id" {
  description = "Bedrock model ID used by the entity resolver. Override if your account uses a regional inference profile."
  type        = string
  default     = "anthropic.claude-3-5-sonnet-20241022-v2:0"
}

variable "bedrock_embedding_model_id" {
  description = "Bedrock text embedding model for SAM.gov SOW enrichment when sam_embedding_provider is bedrock."
  type        = string
  default     = "amazon.titan-embed-text-v1"
}

variable "proposal_writer_provider" {
  description = "Proposal Writer generation backend. bedrock uses Nova Lite preprocessing plus Sonnet drafting; template keeps deterministic fallback only."
  type        = string
  default     = "bedrock"

  validation {
    condition     = contains(["bedrock", "template"], var.proposal_writer_provider)
    error_message = "proposal_writer_provider must be bedrock or template."
  }
}

variable "proposal_writer_model_id" {
  description = "Bedrock model ID or inference profile for fast Proposal Writer drafts."
  type        = string
  default     = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
}

variable "proposal_escalation_model_id" {
  description = "Bedrock model ID or inference profile for quality escalation when the fast Proposal Writer draft does not pass checks."
  type        = string
  default     = "us.anthropic.claude-sonnet-4-6"
}

variable "proposal_helper_model_id" {
  description = "Bedrock model ID for low-cost Section L/M extraction and opportunity/evidence summarization."
  type        = string
  default     = "amazon.nova-lite-v1:0"
}

variable "proposal_fallback_model_id" {
  description = "Bedrock model ID for cheap Proposal Writer fallback before deterministic templates."
  type        = string
  default     = "amazon.nova-pro-v1:0"
}

variable "proposal_job_ttl_seconds" {
  description = "Seconds before Proposal Writer async job records expire from DynamoDB."
  type        = number
  default     = 2592000
}

variable "sam_embedding_provider" {
  description = "Embedding provider for SAM.gov opportunity enrichment. deterministic is no-cost; bedrock uses the configured embedding model."
  type        = string
  default     = "deterministic"

  validation {
    condition     = contains(["deterministic", "bedrock"], var.sam_embedding_provider)
    error_message = "sam_embedding_provider must be deterministic or bedrock."
  }
}

variable "auth_required" {
  description = "When true, the API Lambda enforces Bearer JWT validation through JWKS."
  type        = bool
  default     = false
}

variable "jwt_issuer" {
  description = "Expected JWT issuer, for example a Cognito user pool or Cloudflare Access issuer."
  type        = string
  default     = ""
}

variable "jwt_audience" {
  description = "Expected JWT audience/client ID."
  type        = string
  default     = ""
}

variable "jwt_jwks_url" {
  description = "JWKS URL used by the API Lambda for token signature validation."
  type        = string
  default     = ""
}

variable "jwt_tenant_claim" {
  description = "JWT claim containing the CaptureOS tenant slug."
  type        = string
  default     = "https://captureos/tenant"
}

variable "jwt_role_claim" {
  description = "JWT claim containing the CaptureOS role."
  type        = string
  default     = "https://captureos/role"
}

variable "enable_api_gateway_jwt_authorizer" {
  description = "Attach API Gateway v2 JWT authorizer to all routes. Requires jwt_issuer and jwt_audience."
  type        = bool
  default     = false
}

variable "sam_api_key_secret_arn" {
  description = "Optional Secrets Manager ARN containing the SAM.gov API key. Use key SAM_API_KEY for JSON secrets."
  type        = string
  default     = ""
}

variable "stripe_api_key_secret_arn" {
  description = "Optional Secrets Manager ARN containing the Stripe API key. Use key STRIPE_API_KEY for JSON secrets."
  type        = string
  default     = ""
}

variable "stripe_webhook_secret_arn" {
  description = "Optional Secrets Manager ARN containing the Stripe webhook signing secret. Use key STRIPE_WEBHOOK_SECRET for JSON secrets."
  type        = string
  default     = ""
}

variable "stripe_price_id" {
  description = "Stripe recurring price ID used for hosted checkout."
  type        = string
  default     = ""
}

variable "app_public_url" {
  description = "Public frontend URL used for billing success/cancel redirects."
  type        = string
  default     = "https://pursuitdesk.pages.dev"
}

variable "enable_gsa_ingest_schedule" {
  description = "Create a low-cost EventBridge Scheduler job for live SAM.gov opportunity ingestion."
  type        = bool
  default     = false
}

variable "gsa_ingest_schedule_expression" {
  description = "EventBridge Scheduler expression for live SAM.gov opportunity ingestion."
  type        = string
  default     = "rate(6 hours)"
}

variable "gsa_ingest_lookback_days" {
  description = "Number of posted-date days the scheduled SAM.gov ingestion scans each run."
  type        = number
  default     = 1
}

variable "gsa_ingest_max_pages" {
  description = "Maximum SAM.gov pages to read per scheduled run to keep demo costs bounded."
  type        = number
  default     = 2
}

variable "enable_sam_enrichment_schedule" {
  description = "Create a low-cost EventBridge Scheduler job to enrich live SAM.gov opportunities with SOW text and pgvector embeddings."
  type        = bool
  default     = false
}

variable "sam_enrichment_schedule_expression" {
  description = "EventBridge Scheduler expression for SAM.gov opportunity document enrichment."
  type        = string
  default     = "rate(12 hours)"
}

variable "sam_enrichment_batch_limit" {
  description = "Maximum active SAM.gov opportunities to enrich per scheduled run."
  type        = number
  default     = 10
}

variable "sam_enrichment_fetch_documents" {
  description = "Fetch SAM.gov document URLs during enrichment. Keep false for the no-NAT demo stack; metadata-only embeddings still run inside the VPC."
  type        = bool
  default     = false
}

variable "enable_usaspending_awards_schedule" {
  description = "Create a low-cost EventBridge Scheduler job for USAspending contract award ingest."
  type        = bool
  default     = false
}

variable "usaspending_awards_schedule_expression" {
  description = "EventBridge Scheduler expression for USAspending award ingest."
  type        = string
  default     = "rate(24 hours)"
}

variable "usaspending_awards_lookback_days" {
  description = "Number of award start-date days the scheduled USAspending ingest scans each run."
  type        = number
  default     = 30
}

variable "usaspending_awards_max_pages" {
  description = "Maximum USAspending pages to read per scheduled run."
  type        = number
  default     = 5
}

variable "enable_usaspending_subawards_schedule" {
  description = "Create a low-cost EventBridge Scheduler job for FSRS-derived USAspending subaward ingest."
  type        = bool
  default     = false
}

variable "usaspending_subawards_schedule_expression" {
  description = "EventBridge Scheduler expression for FSRS-derived USAspending subaward ingest."
  type        = string
  default     = "rate(24 hours)"
}

variable "usaspending_subawards_lookback_days" {
  description = "Number of subaward date days the scheduled USAspending subaward ingest scans each run."
  type        = number
  default     = 365
}

variable "usaspending_subawards_max_pages" {
  description = "Maximum USAspending subaward pages to read per scheduled run."
  type        = number
  default     = 5
}

variable "enable_gsa_calc_schedule" {
  description = "Create a low-cost EventBridge Scheduler job for GSA CALC+ labor ceiling-rate ingest."
  type        = bool
  default     = false
}

variable "gsa_calc_schedule_expression" {
  description = "EventBridge Scheduler expression for GSA CALC+ labor ceiling-rate ingest."
  type        = string
  default     = "rate(24 hours)"
}

variable "gsa_calc_keywords" {
  description = "Labor-category keywords to query from GSA CALC+ per scheduled run."
  type        = list(string)
  default = [
    "program manager",
    "project manager",
    "business analyst",
    "systems engineer",
    "data scientist",
    "cloud architect",
    "cyber security",
    "devsecops",
    "logistics analyst",
    "construction manager",
    "estimator"
  ]
}

variable "gsa_calc_max_pages" {
  description = "Maximum GSA CALC+ pages to read per keyword per scheduled run."
  type        = number
  default     = 2
}

variable "gsa_calc_page_size" {
  description = "GSA CALC+ page size per keyword request."
  type        = number
  default     = 100
}

variable "enable_cloudwatch_alarms" {
  description = "Create optional CloudWatch alarms for Lambda errors and API 5xx responses. Disabled by default to avoid idle demo spend."
  type        = bool
  default     = false
}

variable "enable_ingest_failure_alarms" {
  description = "Create focused CloudWatch alarms for scheduled ingest/upsert Lambda failures."
  type        = bool
  default     = false
}

variable "cloudwatch_alarm_actions" {
  description = "Optional CloudWatch alarm action ARNs, such as an SNS topic ARN for email delivery."
  type        = list(string)
  default     = []
}

variable "api_cors_allowed_origins" {
  description = "Allowed browser origins for the HTTP API. Use the Cloudflare-hosted frontend origin in shared demos."
  type        = list(string)
  default     = ["*"]
}

variable "api_throttle_rate_limit" {
  description = "HTTP API steady-state request rate cap to prevent accidental demo spend."
  type        = number
  default     = 25
}

variable "api_throttle_burst_limit" {
  description = "HTTP API burst request cap to prevent accidental demo spend."
  type        = number
  default     = 50
}

locals {
  name_prefix = substr(replace(lower("${var.project_name}-${var.environment}"), "/[^a-z0-9-]/", "-"), 0, 42)

  common_tags = {
    Project     = var.project_name
    Environment = var.environment
    CostProfile = "free-tier-demo"
    ManagedBy   = "terraform"
  }
}
