variable "aws_region" {
  description = "AWS region for the demo stack."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Short project name used in resource names and tags."
  type        = string
  default     = "govcon-captureos"
}

variable "environment" {
  description = "Deployment environment label."
  type        = string
  default     = "demo"
}

variable "vpc_cidr" {
  description = "IPv4 CIDR for the low-cost demo VPC."
  type        = string
  default     = "10.42.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "Two public subnet CIDRs. Lambda and RDS are both placed here to avoid NAT gateways."
  type        = list(string)
  default     = ["10.42.0.0/24", "10.42.1.0/24"]

  validation {
    condition     = length(var.public_subnet_cidrs) == 2
    error_message = "Exactly two public subnet CIDRs are required."
  }
}

variable "db_name" {
  description = "Initial PostgreSQL database name."
  type        = string
  default     = "captureos"

  validation {
    condition     = can(regex("^[A-Za-z][A-Za-z0-9_]{0,62}$", var.db_name))
    error_message = "db_name must start with a letter and contain only alphanumeric characters or underscores."
  }
}

variable "db_username" {
  description = "RDS PostgreSQL master username. The password is generated by Terraform to avoid a hard-coded value."
  type        = string
  default     = "captureos"

  validation {
    condition     = can(regex("^[A-Za-z][A-Za-z0-9_]{0,62}$", var.db_username))
    error_message = "db_username must start with a letter and contain only alphanumeric characters or underscores."
  }
}

variable "postgres_engine_version" {
  description = "PostgreSQL engine version. Keep on 15+ for pgvector support through the database migration."
  type        = string
  default     = "15"

  validation {
    condition     = can(regex("^(1[5-9]|[2-9][0-9])(\\..*)?$", var.postgres_engine_version))
    error_message = "postgres_engine_version must be PostgreSQL 15 or newer."
  }
}

variable "lambda_functions" {
  description = "Lambda deployment artifacts and runtime settings. The api key is wired to API Gateway HTTP API."
  type = map(object({
    package_path         = string
    source_code_hash     = optional(string)
    handler              = string
    runtime              = optional(string, "python3.12")
    memory_size          = optional(number, 256)
    timeout              = optional(number, 20)
    reserved_concurrency = optional(number)
    environment          = optional(map(string), {})
  }))

  default = {
    api = {
      package_path = "../../dist/captureos_api.zip"
      handler      = "src.lambda_api.handler"
      runtime      = "python3.12"
      memory_size  = 256
      timeout      = 20
      environment = {
        APP_MODULE = "src.api_v1_endpoints:app"
      }
    }

    ingest = {
      package_path = "../../dist/captureos_ingest.zip"
      handler      = "src.gsa_api_ingest.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 128
      timeout      = 60
      environment = {
        LOG_LEVEL = "INFO"
      }
    }

    resolver = {
      package_path = "../../dist/captureos_resolver.zip"
      handler      = "src.entity_resolver_lambda.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 256
      timeout      = 30
      environment = {
        ENTITY_RESOLUTION_AUTO_MATCH_SCORE = "0.91"
      }
    }

    db_admin = {
      package_path = "../../dist/captureos_db_admin.zip"
      handler      = "src.db_admin_lambda.lambda_handler"
      runtime      = "python3.12"
      memory_size  = 256
      timeout      = 120
      environment = {
        LOG_LEVEL = "INFO"
      }
    }
  }

  validation {
    condition     = contains(keys(var.lambda_functions), "api")
    error_message = "lambda_functions must include an api function for API Gateway integration."
  }

  validation {
    condition     = alltrue([for fn in values(var.lambda_functions) : contains([128, 256], fn.memory_size)])
    error_message = "Each Lambda memory_size must be 128 or 256 MB for this low-cost demo profile."
  }

  validation {
    condition     = alltrue([for fn in values(var.lambda_functions) : fn.reserved_concurrency == null || (fn.reserved_concurrency >= 10 && fn.reserved_concurrency <= 25)])
    error_message = "When set, reserved_concurrency must be 10-25 so AWS keeps its required unreserved concurrency pool."
  }
}

variable "lambda_layer_arns" {
  description = "Optional dependency layers for psycopg2, FastAPI/Mangum, boto3 extras, or pgvector client packages."
  type        = list(string)
  default     = []
}

variable "lambda_log_retention_days" {
  description = "CloudWatch Logs retention for Lambda logs. Short retention prevents silent storage creep."
  type        = number
  default     = 7
}

variable "bedrock_model_id" {
  description = "Bedrock model ID used by the entity resolver. Override if your account uses a regional inference profile."
  type        = string
  default     = "anthropic.claude-3-5-sonnet-20241022-v2:0"
}

variable "api_cors_allowed_origins" {
  description = "Allowed browser origins for the HTTP API. Use the Cloudflare-hosted frontend origin in shared demos."
  type        = list(string)
  default     = ["*"]
}

variable "api_throttle_rate_limit" {
  description = "HTTP API steady-state request rate cap to prevent accidental demo spend."
  type        = number
  default     = 25
}

variable "api_throttle_burst_limit" {
  description = "HTTP API burst request cap to prevent accidental demo spend."
  type        = number
  default     = 50
}

locals {
  name_prefix = substr(replace(lower("${var.project_name}-${var.environment}"), "/[^a-z0-9-]/", "-"), 0, 42)

  common_tags = {
    Project     = var.project_name
    Environment = var.environment
    CostProfile = "free-tier-demo"
    ManagedBy   = "terraform"
  }
}
